version: "3"

services:
  casebox-allinone:
    build: ./
    ports:
      - "80:80"
      - "33306:3306"
    # NOTE: the next two lines overide original repository with my own version
    #       for debug. Please comment these lines on your setup (fititnt, 2018-04-09 02:12 BRT)
#    volumes:
#      - /alligo/code/fititnt/casebox:/var/www/casebox/

#    volumes:
#      - ./data/mysql/:/var/lib/mysql
#    # NOTE: the next line overide original repository with my own version
#    #       for debug. Please comment this line on your setup (fititnt, 2018-04-10 02:33 BRT)
#    #  - /alligo/code/fititnt/casebox:/var/www/casebox/
