# All-in-One Casebox Dockerfile
# Note: Dockerfile best practices (https://docs.docker.com/develop/develop-images/dockerfile_best-practices)
#       suggest do not use All-in-one containers, but we will just try follow
#       https://github.com/KETSE/casebox/wiki/Ubuntu-14.04-x64
#       instructions for now (fititnt, 2018-04-08 00:48 BRT)

FROM ubuntu:14.04
MAINTAINER "Emerson Rocha <rocha@ieee.org>"
